# Exported from Render on 2024-12-27T19:50:28Z
services:
  - type: web
    name: my-service
    env: python
    pythonVersion: 3.8.0
    buildCommand: |
     python -m pip install --upgrade pip
      pip install -r requirements.txt

